### PR TITLE
[9.x] Rerender

### PR DESCRIPTION
**Pull request by jdblischak**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

---

It's my understanding that the [9.0.x](https://github.com/conda-forge/arrow-cpp-feedstock/tree/9.0.x) branch is still actively maintained. We are getting solver errors because arrow 9 is built against libabseil 20230125, but conda-forge-pinning now builds packages against [libabseil 20230802](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/c8b789428ede8f040d00f4b84cfce21668fe9ef6/recipe/conda_build_config.yaml#L428). Both arrow 10 and 11 are also building against the latest 20230802.

I started by doing a full rerender. If this is too much change, I can try only bumping the libabseil pin

### CODE REVIEW

**Comment by h-vetinari** [comment]
> It's my understanding that the [9.0.x](https://github.com/conda-forge/arrow-cpp-feedstock/tree/9.0.x) branch is still actively maintained.

That is incorrect. We support the last 4 versions, which currently are 11-14 (also reflected [here](https://github.com/conda-forge/arrow-cpp-feedstock/blob/main/conda-forge.yml)). That said, if you can bring this PR to green with changes that aren't too crazy, I'm fine to merge it exceptionally. :)

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

Sidenote: don't manually edit the files in `.ci_support`, they should be changed by the bot. First and foremost, you'll want the versions from the global pinning (happens by default), though you can override them by copying relevant open migrators under `.ci_support/migrators` (like the migration for grpc/protobuf that's almost done), or by setting values in `conda_build_config.yaml`.

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by jdblischak** [comment]
> That is incorrect. We support the last 4 versions, which currently are 11-14 (also reflected [here](https://github.com/conda-forge/arrow-cpp-feedstock/blob/main/conda-forge.yml)).

@h-vetinari Thanks for clarifying! Since the README is auto-generated by conda-smithy, I wasn't sure where to look for this documentation. I guessed based on the fact that the most recent commit to `9.0.x`, https://github.com/conda-forge/arrow-cpp-feedstock/commit/901e4eb32c875aa40aea1a156c63e1230ee7ebf5, was made 3 months ago

> That said, if you can bring this PR to green with changes that aren't too crazy, I'm fine to merge it exceptionally. :)

I got us nowhere close to green, but your changes have everything working except for Windows. Do you have a sense if the Windows errors are surmountable? This PR would be a nice-to-have, but I recognize that it is a longshot. I'm happy to help troubleshoot and test however I can

**Comment by jdblischak** [comment]
> Sidenote: don't manually edit the files in `.ci_support`, they should be changed by the bot.

I apologize for the confusion. I started by a traditional rerender, which made a lot of changes, so I overwrote history to make some point changes. Essentially I was just testing for feasibility. I should have marked the PR `[WIP]` or something like that so that you and other maintainers would know I wasn't suggesting it be merged as it was

**Comment by h-vetinari** [comment]
> Do you have a sense if the Windows errors are surmountable?

Surmountable definitely - after all, newer arrow builds with abseil 20230802 -, but not worth the (with arrow problems often substantial) effort IMO. Unless you exactly need this build for windows, I'd be fine to add a `skip: true  # [win]` here and call it a day.

**Comment by jdblischak** [comment]
> Unless you exactly need this build for windows, I'd be fine to add a `skip: true # [win]` here and call it a day.

I'd rather get Linux and macOS builds than nothing. I could always return to Windows troubleshooting later if necessary.

I skipped Windows and rerendered. Do you plan to squash and merge the commits? If not, I can clean up the Git history prior to merging

**Comment by h-vetinari** [comment]
> Do you plan to squash and merge the commits? If not, I can clean up the Git history prior to merging

It's true that I try to keep the feedstock histories clean, but this PR is actually pretty OK.

Hope the rerender helps your usecase. If something breaks, we'll very likely have to mark these as broken (we weren't running the full test suite until v10, so I'm a bit queasy about the coverage). In any case, knock wood!

**Pull request merged**
