### PR TITLE
Update to version 0.13.0

### PR DESCRIPTION
**Pull request by kszucs**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kszucs** [comment]
I think the windows builds depend on https://github.com/conda-forge/conda-forge.github.io/issues/703 and https://github.com/Microsoft/azure-pipelines-image-generation/pull/728

**Comment by wesm** [comment]
The Azure Windows builds failed on master. Can this be merged in the meantime?

**Comment by kszucs** [comment]
@wesm I suppose. I've removed gandiva support, because different clang versions were picked up on osx and linux to compile `gandiva/precompiled`. I will submit another PR here with bumped build number after I fully test the gandiva support in https://github.com/apache/arrow/pull/4046

**Comment by kszucs** [comment]
Or You can wait me for incorporate the changes, beacuse it looks like they are already working:
- [osx](https://travis-ci.org/kszucs/crossbow/builds/514069524#L713)
- [linux](https://travis-ci.org/kszucs/crossbow/builds/514069524#L713)

The trick was: https://github.com/apache/arrow/pull/4046/commits/26240e1910f8dcc0b0e516ecaa0b934a2b1cda10

**Comment by wesm** [comment]
Yes I think it's fine to omit gandiva here for now

**Comment by kszucs** [comment]
Reverted.

**Comment by kszucs** [comment]
@wesm unix builds pass

**Comment by wesm** [comment]
sweet thanks @kszucs!

**Pull request merged**
