### PR TITLE
Join as maintainer to take care of migrations

### PR DESCRIPTION
**Pull request by h-vetinari**
Hey all

There's currently a few tricky migrations pending (abseil, grpc, libprotobuf), and since arrow plays such a central role in the ecosystem nowadays, it's good to keep this moving along across all ABI branches. Not least since I also help co-maintain those other feedstocks, I'd be happy to help take care of these migrations, and this would be easier as a maintainer (can push into bot PRs, no need for attention on trivial PRs).

I thought I'd propose joining first (considering the quantity of open migration PRs), but if desired I can also try raising independent PRs first.

PS. I'm not completely new to this feedstock, c.f. https://github.com/conda-forge/arrow-cpp-feedstock/pull/247 & collab on https://github.com/conda-forge/pyarrow-feedstock/pull/101. :)

PPS. A standard rerender seems to bring in the (now-closed) orc migration; if desired I can undo this part.

Closes #826

### CODE REVIEW

**Comment by h-vetinari** [comment]
> @h-vetinari Can you please also apply [6643cec](https://github.com/conda-forge/arrow-cpp-feedstock/commit/6643ceccfeba50f7a114ad4f7fc4ff1e19fa613c) here to limit parallelism on Azure? Otherwise, we will block the whole of conda-forge.

Fine in principle, but that's gonna make it very painful to move through all the migrations (though as soon as we do the abseil one, we'll be dropping half the jobs) - I've worked concurrently on big CI matrices in conda-forge before (e.g. the BLAS-testing PRs in numpy/scipy) and never noticed that other feedstocks didn't start, so I'm not sure where the limit lies, but it seems to be pretty high.

Do you know if the `max_parallel:` is per platform (in which case I would say it's barely doable), or for the whole pipeline (in which case I think the limit is not reasonable).

PS. Windows builds here need https://github.com/conda-forge/admin-requests/pull/482.

**Comment by h-vetinari** [comment]
> Do you know if the `max_parallel:` is per platform

Looks like it's for the whole pipeline: https://github.com/conda-forge/conda-smithy/blob/v3.21.1/conda_smithy/configure_feedstock.py#L1343-L1345

Currently there are 70 jobs, and the aarch/ppc ones take almost 5-6h based on the last successful run. With a limit of 8, that would mean waiting up to >48h for one CI job to finish, which is not reasonable IMO (considering the number of branches & migrations outstanding). I think 30 parallel jobs would be manageable, both for waiting time & the rest of conda-forge.

**Comment by xhochy** [comment]
> > Do you know if the `max_parallel:` is per platform
> 
> Looks like it's for the whole pipeline: https://github.com/conda-forge/conda-smithy/blob/v3.21.1/conda_smithy/configure_feedstock.py#L1343-L1345
> 
> Currently there are 70 jobs, and the aarch/ppc ones take almost 5-6h based on the last successful run. With a limit of 8, that would mean waiting up to >48h for one CI job to finish, which is not reasonable IMO (considering the number of branches & migrations outstanding). I think 30 parallel jobs would be manageable, both for waiting time & the rest of conda-forge.

Then set it to 30 jobs for now. We should limit the parallelism on this feedstock though as very briefly summarised in https://github.com/conda-forge/arrow-cpp-feedstock/issues/825

**Comment by h-vetinari** [comment]
@xhochy, regarding the clang version used here, I needed to bump away from 10 at least on windows (VS2019 needs clang>=11), and decided to give it a shot with 14. It seems this is working without issue, but does this need to be checked somehow, or should I restrict this bump to windows?

I saw in the build scripts that there were some [comments](https://github.com/conda-forge/arrow-cpp-feedstock/blame/main/recipe/build-arrow.sh#L38) along the lines of "We need llvm 11+ support in Arrow for this" (for osx-arm), but since that [commit](https://github.com/conda-forge/arrow-cpp-feedstock/commit/fa7b5e2af17fa2c4d54a6bc8d66ccef0a9472e5e) is almost 2 years old, I guess it might be time to revisit this?

Ideally, the osx-arm parts would be changed in a different PR. It's gonna be another ~10h until the aarch/ppc builds are through, and merging this one would allow me to tackle the other branches in the meantime.

**Comment by h-vetinari** [comment]
All the failures / timeouts here are flaky and can be fixed by restarts after merging (if they reoccur). IMO this is good to go (pending the clang 10->14 question).

**Comment by xhochy** [comment]
> I saw in the build scripts that there were some [comments](https://github.com/conda-forge/arrow-cpp-feedstock/blame/main/recipe/build-arrow.sh#L38) along the lines of "We need llvm 11+ support in Arrow for this" (for osx-arm), but since that [commit](https://github.com/conda-forge/arrow-cpp-feedstock/commit/fa7b5e2af17fa2c4d54a6bc8d66ccef0a9472e5e) is almost 2 years old, I guess it might be time to revisit this?

Yes 😂

**Comment by h-vetinari** [comment]
> > I saw in the build scripts that there were some [comments](https://github.com/conda-forge/arrow-cpp-feedstock/blame/main/recipe/build-arrow.sh#L38) along the lines of "We need llvm 11+ support in Arrow for this" (for osx-arm), but since that [commit](https://github.com/conda-forge/arrow-cpp-feedstock/commit/fa7b5e2af17fa2c4d54a6bc8d66ccef0a9472e5e) is almost 2 years old, I guess it might be time to revisit this?
> 
> Yes 😂

Let's tackle this after the migrations. 🙃

**Pull request merged**
