### PR TITLE
Add raulcd as recipe maintainer

### PR DESCRIPTION
**Pull request by raulcd**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by raulcd** [comment]
@h-vetinari as Arrow PMC doing the releases, should I be added here to try and help?

**Review by xhochy — APPROVED** [review]
Yes

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Review by h-vetinari — APPROVED** [review]
> as Arrow PMC doing the releases, should I be added here to try and help?

Absolutely, and welcome!

**Comment by h-vetinari** [comment]
Given the failing CI, I pushed this manually in https://github.com/conda-forge/arrow-cpp-feedstock/commit/e82f9da5f58e5539289b7f6c5dc4e1e15939505b.

**Pull request closed without merging**
