### PR TITLE
[main] Rebuild for libabseil20230125

### PR DESCRIPTION
**Pull request by h-vetinari**
Bot stuck on tensorflow

### CODE REVIEW

**Comment by h-vetinari** [comment]
It seems this is segfaulting in `test_flight.py::test_flight_list_flights` on osx-64 both for arrow 10 & 11, might be related to https://github.com/conda-forge/grpc-cpp-feedstock/issues/281, which I haven't had time to look into yet...

CC @xhochy @kkraus14 @kou @pitrou @coryan

**Comment by h-vetinari** [comment]
> It seems this is segfaulting in `test_flight.py::test_flight_list_flights` on osx-64 both for arrow 10 & 11

Looking at the [source](https://github.com/apache/arrow/blob/apache-arrow-11.0.0/python/pyarrow/tests/test_flight.py#L911-L917) of that test and the utility class [`ConstantFlightServer`](https://github.com/apache/arrow/blob/apache-arrow-11.0.0/python/pyarrow/tests/test_flight.py#L128-L133), it notes:
>  See ARROW-4796: this server implementation will segfault if Flight
    does not properly hold a reference to the Table object.

**Comment by h-vetinari** [comment]
@kou @pitrou 
Any idea what might be causing these segfaults on osx? This is now holding up other migrations like re2... 😢

**Comment by h-vetinari** [comment]
@conda-forge/arrow-cpp @kou @pitrou @jorisvandenbossche @kkraus14 

A lot of migrations are starting to pile up on the missing abseil migration for arrow 10/11. I'm going to skip the flight tests on osx now to unblock this. Any input/help is welcome.

**Comment by kkraus14** [comment]
> @conda-forge/arrow-cpp @kou @pitrou @jorisvandenbossche @kkraus14
> 
> A lot of migrations are starting to pile up on the missing abseil migration for arrow 10/11. I'm going to skip the flight tests on osx now to unblock this. Any input/help is welcome.

I'll ping a few folks internally to see if I can get someone to jump in here.

**Comment by h-vetinari** [comment]
> I'll ping a few folks internally to see if I can get someone to jump in here.

@kkraus14, not sure what ever came of this, but there's now an upstream issue to track this: https://github.com/apache/arrow/issues/36908

**Pull request merged**
