### PR TITLE
Update activation failure warning

### PR DESCRIPTION
**Pull request by maresb**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
Thanks for the PR! :)
As I said in https://github.com/h-vetinari/arrow-cpp-feedstock/pull/1, I'll just fold this into the next batch of PRs. I don't think it's worth an extra build on its own.

**Comment by maresb** [comment]
Agreed, thanks!

**Comment by maresb** [comment]
Oh... maybe I shouldn't have closed this if you wanted the placeholder / test verification? Please reopen if you want.

**Comment by h-vetinari** [comment]
> Oh... maybe I shouldn't have closed this if you wanted the placeholder / test verification? Please reopen if you want.

It's already in #1124. ;-)

**Pull request closed without merging**
