### PR TITLE
Update to v15.0.1

### PR DESCRIPTION
**Pull request by raulcd**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by raulcd** [comment]
I'll rebase once the cython fix is merged on main.

**Comment by h-vetinari** [comment]
> I'll rebase once the cython fix is merged on main.

Could you specify which fix and which main branch (here or upstream)?

**Comment by raulcd** [comment]
> Could you specify which fix and which main branch (here or upstream)?

Sorry I meant this commit (https://github.com/conda-forge/arrow-cpp-feedstock/pull/1335/commits/f228614617d050cba108d159136f39c6c2011830) on this PR: https://github.com/conda-forge/arrow-cpp-feedstock/pull/1335

**Comment by raulcd** [comment]
@h-vetinari this should be ready to merge now

**Review by h-vetinari — APPROVED** [review]

**Comment by h-vetinari** [comment]
Thanks! :)

**Pull request merged**
