### PR TITLE
add abseil to pyarrow host section

### LINKED ISSUE #814: PyArrow builds aren't correctly pinning to the locally produced arrow-cpp build
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

For example, see here: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=538009&view=logs&j=3b077b59-19b3-5c3c-d9ea-4f2d359714ca&t=4427250c-9566-5227-2be0-fd328c273206

This produced 4 packages:
```
    /home/conda/feedstock_root/build_artifacts/linux-64/arrow-cpp-8.0.1-py39h2531139_0_cpu.tar.bz2
    /home/conda/feedstock_root/build_artifacts/linux-64/arrow-cpp-proc-3.0.0-cpu.tar.bz2
    /home/conda/feedstock_root/build_artifacts/linux-64/pyarrow-8.0.1-py39h42d110c_0_cpu.tar.bz2
    /home/conda/feedstock_root/build_artifacts/linux-64/pyarrow-tests-8.0.1-py39h42d110c_0_cpu.tar.bz2
```

If we look at the `pyarrow-8.0.1-py39h42d110c_0_cpu` build we can see that it pins to the incorrect `arrow-cpp` build:
```
pyarrow 8.0.1 py39h42d110c_0_cpu
--------------------------------
file name   : pyarrow-8.0.1-py39h42d110c_0_cpu.tar.bz2
name        : pyarrow
version     : 8.0.1
build       : py39h42d110c_0_cpu
build number: 0
size        : 3.3 MB
license     : Apache-2.0
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/pyarrow-8.0.1-py39h42d110c_0_cpu.tar.bz2
md5         : f8e42cd6b5bee024305502104efba504
timestamp   : 2022-07-29 21:55:46 UTC
constraints :
  - arrow-cpp-proc * cpu
dependencies:
  - arrow-cpp 8.0.1 py39h811ffd7_0_cpu
  - libgcc-ng >=12
  - libstdcxx-ng >=12
  - numpy >=1.16,<2.0a0
  - numpy >=1.19.5,<2.0a0
  - parquet-cpp 1.5.1.*
  - python >=3.9,<3.10.0a0
  - python_abi 3.9.* *_cp39
```

This is causing issues where for example we're building `arrow-cpp` with two abseil versions, but the `pyarrow` builds are only depending on `arrow-cpp` packages built against one of those abseil versions.

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

### PR DESCRIPTION
**Pull request by kkraus14**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Fixes #814. Adds abseil to the pyarrow host section to get it to properly parametrize on arrow-cpp build variants to prevent issues where we can't use certain abseil versions because pyarrow only pins to other version arrow-cpp builds.

### CODE REVIEW

**Comment by kkraus14** [comment]
@conda-forge-admin please rerender

**Comment by kkraus14** [comment]
Once we confirm this fixes the problem I'll backport it to 8.x, 7.x, and 6.x.

**Comment by kkraus14** [comment]
Based on logs this seems to resolve the issue of clobbering the pyarrow builds:

### Arrow 8.0.1 build logs:
- [linux_64_abseil_cpp20211102.0c_compiler_version10cuda_compiler_versionNonecxx_compiler_version10grpc_cpp1.46numpy1.21python3.10.____cpython](https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/546074/logs/292)
  - pyarrow build: `pyarrow-8.0.1-py310h225c066_0_cpu`
- [linux_64_abseil_cpp20210324.2c_compiler_version10cuda_compiler_versionNonecxx_compiler_version10grpc_cpp1.45numpy1.21python3.10.____cpython](https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/546074/logs/261)
  - pyarrow build: `pyarrow-8.0.1-py310h225c066_0_cpu`

### This PR build logs
- [linux_64_abseil_cpp20211102.0c_compiler_version10cuda_compiler_versionNonecxx_compiler_version10grpc_cpp1.46numpy1.21python3.10.____cpython](https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/547696/logs/294)
  - pyarrow build: `pyarrow-9.0.0-py310had720df_1_cpu`
- [linux_64_abseil_cpp20210324.2c_compiler_version10cuda_compiler_versionNonecxx_compiler_version10grpc_cpp1.45numpy1.21python3.10.____cpython](https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/547696/logs/273)
  - pyarrow build: `pyarrow-9.0.0-py310h580ff74_1_cpu`

**Comment by kkraus14** [comment]
Only builds left are the emulated builds that tend to time out, so this should be ready for review

**Review by cpcloud — APPROVED** [review]
I'll admit I am not entirely sure what the implications of this are, other than that the host closure is `sizeof(abseil-cpp)` bigger.

Since it unblocks you, I'll approve.

**Comment by pitrou** [comment]
What is a "host" dependency as opposed to "build" and "run"?

**Comment by kkraus14** [comment]
> What is a "host" dependency as opposed to "build" and "run"?

See here: https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#build

**Comment by pitrou** [comment]
> See here: https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#build

Ironically this section manages to be both quite verbose and still cryptic :-(

Also, why is Abseil listed there? Abseil would either be a build-time (compile) dependency or run-time (dynamic library) dependency, but I don't understand why it would be a "host" dependency.

**Comment by kkraus14** [comment]
> Ironically this section manages to be both quite verbose and still cryptic :-(

The way I think about it is:
* `build` section is for things that need to be on the *native* platform like executables and cdt packages. Typically this means things like the compilers, cmake, make/ninja, etc. end up in this section. Say we're cross compiling for aarch64 on an x64 machine, these would be x64 packages.
* `host` section is for things that are needed at build time for the *target* platform. Typically this means shared libraries, headers, python packages needed for building extensions, etc. Say we're cross compiling for aarch64 on an x64 machine, these would be aarch64 packages.
* `run` section is for things needed during runtime in using the package.

> Also, why is Abseil listed there? Abseil would either be a build-time (compile) dependency or run-time (dynamic library) dependency, but I don't understand why it would be a "host" dependency.

This is a workaround for a bug in conda-build. Conda-build generates a hash for building a package based on the package versions in the recipe. For some reason, it doesn't include the arrow-cpp version when generating that hash which is exactly pinned in the pyarrow recipe to a specific build. Unfortunately, without the arrow-cpp version being included, it leads to two pyarrow packages having the same hash that require different arrow-cpp packages, which are differentiated by their abseil and grpc-cpp versions (see here: https://github.com/conda-forge/arrow-cpp-feedstock/pull/815#issuecomment-1208434493). To workaround this bug, we add abseil-cpp to the pyarrow `host` section to get it to be factored into the pyarrow pkg hash which allows pyarrow pkgs to be produced for the differentiated arrow-cpp pkgs.

**Comment by jakirkham** [comment]
In terms of the docs being confusing, would suggest raising [an issue on the conda-build repo]( https://github.com/conda/conda-build/issues/new ) with a bit more context about what is confusing and why. If you happen to have suggestions on how to improve it (after Keith explained these sections above), that would also be helpful information to capture 🙂

**Pull request merged**
