### PR TITLE
Windows + Cuda [Branch 1.0.x]

### PR DESCRIPTION
**Pull request by h-vetinari**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Cherry-picked the commits from #247 (aside from the rerender) into #263.

Closes #263

### CODE REVIEW

**Comment by h-vetinari** [comment]
@xhochy, I thought I'd open one for `1.0.x` as well - or is support on master enough? The migrator also opened one for `0.17` - does that really need win+cuda?

**Review by xhochy — APPROVED** [review]
+1, Thanks!

**Comment by xhochy** [comment]
> @xhochy, I thought I'd open one for `1.0.x` as well - or is support on master enough? The migrator also opened one for `0.17` - does that really need win+cuda?

I'm not aware who would use that. Personally, I need `pyarrow=0.17` for cases thus I maintain that branch but I don't have any Windows or GPU needs.

**Comment by h-vetinari** [comment]
> @xhochy: I'm not aware who would use that. Personally, I need `pyarrow=0.17` for cases thus I maintain that branch but I don't have any Windows or GPU needs.

Agreed; then you can just close #262.

**Pull request merged**
