### PR TITLE
Added cuda compiler for ppc64le arch

### PR DESCRIPTION
**Pull request by alhad-deshpande**
1. Added cuda_compiler_version for ppc64le arch so that arrow-cuda is enabled.
2. Ran conda smithy renderer to generate modified yaml files for ppc64le.
3. Bumped up the build version in meta.yaml file.

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by xhochy — CHANGES_REQUESTED** [review]
No, please use the migration for this.

**Comment by alhad-deshpande** [comment]
> No, please use the migration for this.

@xhochy 
Can you please help me with the process of the migration?

**Comment by xhochy** [comment]
I would have expected something like https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/cuda92_100_101.yaml to also exist for ppc64le but also cannot find it. Maybe search for issues on that repo or on the conda-forge.github.io repo for the proposed process for adding CUDA for ppc64le.

**Comment by alhad-deshpande** [comment]
> > I would have expected something like https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/cuda92_100_101.yaml to also exist for ppc64le but also cannot find it. Maybe search for issues on that repo or on the conda-forge.github.io repo for the proposed process for adding CUDA for ppc64le.
> 
> @xhochy Do you expect the entries for ppc64le in the same https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/cuda92_100_101.yaml file because docker images are available at https://quay.io/repository/condaforge/linux-anvil-ppc64le-cuda?tag=10.2&tab=tags?

**Comment by alhad-deshpande** [comment]
@xhochy 
If migration is added for ppc64le in https://github.com/conda-forge/conda-forge-pinning-feedstock then it will start pinning to all applicable packages, will that be Ok? Instead I thought to have changes only for arrow packages.

Please let me know your views.

**Comment by alhad-deshpande** [comment]
> I would have expected something like https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/cuda92_100_101.yaml to also exist for ppc64le but also cannot find it. Maybe search for issues on that repo or on the conda-forge.github.io repo for the proposed process for adding CUDA for ppc64le.

@xhochy 
I have raised PR on conda-forge-pinning-feedstock for ppc64le arch to be able to build arrow with CUDA. Please have a look.
PR Link: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2527

**Comment by jakirkham** [comment]
A migrator has since been added. Tried to use it in PR ( https://github.com/conda-forge/arrow-cpp-feedstock/pull/723 ). However re-rendering ran into an issue there.

**Comment by h-vetinari** [comment]
I have a working solution for PPC+CUDA in #859. I'd like to still spend some time on trying to figure out cross-compilation, because otherwise this feedstock becomes basically infeasible to build.

**Pull request closed without merging**
