### PR TITLE
LLVM license

### LINKED ISSUE #95: LLVM License violation
Please include the license of LLVM as arrow-cpp is statically linking to it and is a requirement of the MIT and UIUC licenses.

Note that conda-build can include multiple files as a yaml list in in `license_file`.

### PR DESCRIPTION
**Pull request by kszucs**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Resolves #95

### CODE REVIEW

**Comment by kszucs** [comment]
@conda-forge-admin please serenader

**Comment by kszucs** [comment]
cc @xhochy

**Comment by isuruf** [comment]
Note that the license will change in LLVM 9.0.0.

**Comment by xhochy** [comment]
> Note that the license will change in LLVM 9.0.0.

The license here is about code we include in Arrow not about things we link Arrow, too.

**Pull request merged**
