### PR TITLE
Fix osx-arm64 build

### PR DESCRIPTION
**Pull request by xhochy**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
@jakirkham @kkraus14 @pearu @h-vetinari I unpinned CMake and now CUDA isn't found correctly anymore. Do you have suggestions on how to fix that?

```
-- Found Backtrace: /home/conda/feedstock_root/build_artifacts/arrow-cpp-ext_1608127253776/_build_env/x86_64-conda-linux-gnu/sysroot/usr/include  
CMake Error at /home/conda/feedstock_root/build_artifacts/arrow-cpp-ext_1608127253776/_build_env/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find CUDA (missing: CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (found
  version "9.2")
Call Stack (most recent call first):
  /home/conda/feedstock_root/build_artifacts/arrow-cpp-ext_1608127253776/_build_env/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:577 (_FPHSA_FAILURE_MESSAGE)
  /home/conda/feedstock_root/build_artifacts/arrow-cpp-ext_1608127253776/_build_env/share/cmake-3.19/Modules/FindCUDA.cmake:1121 (find_package_handle_standard_args)
  src/arrow/gpu/CMakeLists.txt:32 (find_package)
```

**Comment by jakirkham** [comment]
Is Arrow using [FindCUDA]( https://cmake.org/cmake/help/latest/module/FindCUDA.html )? If so, it may to use CUDA as a language support (analogous to C/C++) in CMake along with [`FindCUDAToolkit`]( https://cmake.org/cmake/help/latest/module/FindCUDAToolkit.html#module:FindCUDAToolkit ) for specific libraries.

**Comment by kkraus14** [comment]
> Is Arrow using [FindCUDA](https://cmake.org/cmake/help/latest/module/FindCUDA.html)? If so, it may to use CUDA as a language support (analogous to C/C++) in CMake along with [`FindCUDAToolkit`](https://cmake.org/cmake/help/latest/module/FindCUDAToolkit.html#module:FindCUDAToolkit) for specific libraries.

IIRC Arrow has no device code so it doesn't need to find `nvcc` in any way. It needs to just find the libs and headers for use in host code by the host compiler.

**Comment by h-vetinari** [comment]
Had similar problems (IIRC) with cuda-detection in https://github.com/conda-forge/faiss-split-feedstock/pull/17 &  https://github.com/conda-forge/faiss-split-feedstock/pull/19.

In the the former, @beckermr, helped me with the following workaround (the surrounding comment contains a bunch more information):
https://github.com/conda-forge/faiss-split-feedstock/blob/master/recipe/build-lib.sh#L44-L52
Since then, there have been a couple of improvements to the nvcc-wrapper already (particularly on windows), but I tested only a few days ago to remove the workaround, and it still fails.

There's an additional wrinkle regarding `FindCUDA`, which @jaimergp mentioned in https://github.com/conda-forge/faiss-split-feedstock/pull/19:
> Unfortunately that verbose flag is for the deprecated `FindCUDA` module, not the current `FindCUDAToolkit`.

There, we ended up using `set "CudaToolkitDir=%CUDA_PATH%"`, but that was only relevant for Windows.

**Comment by jaimergp** [comment]
AFAIK `openmm` also uses the deprecated `FindCUDA`, and we need (or needed) these two variables: https://github.com/conda-forge/openmm-feedstock/blob/master/recipe/build.sh#L19-L22

Maybe the stubs path is not needed anymore but I haven't checked. That should work (as of last week) although I haven't tried with last CMake yet.

**Comment by jaimergp** [comment]
TIL about that [undocumented option](https://github.com/conda/conda-build/issues/2735) which was possibly behind https://github.com/conda-forge/nvcc-feedstock/issues/53 o.o

**Comment by xhochy** [comment]
Seems like the culprit is hidden somewhere in `${CMAKE_ARGS}`. I'll investigate that in another PR.

**Pull request merged**
