### PR TITLE
update to 0.2.0

### PR DESCRIPTION
**Pull request by leifwalsh**

### CODE REVIEW

**Comment by wesm** [comment]
I'll check on this periodically to get the build into master. I can add you as a maintainer on this repo after the update if you'd like

**Comment by wesm** [comment]
Still keeping an eye on this -- would be nice to know where we stand in the build queue at least =/

**Comment by wesm** [comment]
I think we had bad timing because automated feedstock maintenance (re-rendering with new version of conda-smithy) is jamming up the build queue

**Comment by leifwalsh** [comment]
Ok this is pretty ridiculous though.

**Pull request merged**
