### PR TITLE
Set correct pagesize for jemalloc on osx-arm64

### PR DESCRIPTION
**Pull request by xhochy**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
Doesn't fix the `<jemalloc>: Unsupported system page size` issue

**Comment by isuruf** [comment]
Never mind, it did. Now it's a segfault without any message.

**Comment by xhochy** [comment]
> Never mind, it did. Now it's a segfault without any message.

I did fix the previous segfault in #200 This is now a different issue.

**Comment by isuruf** [comment]
Our daily cron job ran on `pyarrow-2.0.0-py39h53c4050_5_cpu_build` and it failed with a segfault.

**Pull request merged**
