### PR TITLE
arrow 14.0.0 with new setup (more granular libraries; no more legacy outputs)

### LINKED ISSUE #1035: Package some form of "minimal" libarrow?
I just saw that pandas is [considering](https://github.com/pandas-dev/pandas/pull/52711) to hard-depend on pyarrow. This would substantially blow up the footprint of all pandas installs (which is pandas' choice to make), but even more so on conda-forge, because we package more bindings than the wheels[^1].

This is not the first time that this topic has come up, c.f. below:

[^1]: given the difficulty of building arrow, they are effectively uninstallable otherwise, hence the maximalist approach to packaging on this feedstock, resp. in conda-forge in general 

> > @h-vetinari: That said, there's a larger theme here that arrow keeps growing non-trivial dependencies. I guess we could introduce a separate output for a "minimal" arrow (`libarrow-core`?)
>
> @jorisvandenbossche: That's indeed something we have to look at long term, but probably good for a separate issue? (it seems to me that regardless of that, cudatoolkit should never be a dependency for the CPU version?) 
> libarrow itself actually already exists of multiple shared libraries (libarrow, libarrow_dataset, libarrow_flight, etc). So that could be a first way to split it into multiple packages that should be simpler (eg libarrow_flight has some extra dependencies that are not needed for libarrow itself, such as UCX). On the Arrow C++ side itself, we are also working on further splitting the core libarrow in more shared libraries.

_Originally posted by @jorisvandenbossche in https://github.com/conda-forge/arrow-cpp-feedstock/issues/962#issuecomment-1432924187_

### PR DESCRIPTION
**Pull request by h-vetinari**
Combines #1170 with a slimmed-down version of #1175

Closes #1035
Closes #1170 
Closes #1175
Closes #1218

### CODE REVIEW

**Comment by h-vetinari** [comment]
Some review notes:
* the removal of the compat outputs was the plan we took in #1124, to give people some more time to adapt. We'll also be able to introduce a linter-rule for anyone still using `arrow-cpp`.
* gandiva now depends on libllvm
* with @raulcd doing the lion's share, we finally tackled the split of libarrow into more granular components. The only big chunk left to shave off is the dependence on the cloud provider bindings, but that's not ready yet
* the manual distribution of files in `install-libarrow.*` is obviously not pretty and could in principle be largely replaced by conda's `files:` directive, however, it probably doesn't work for _everything_ (e.g. activation scripts and handling the symlink that gets created by `libarrow` during the build of `libarrow-*`).
* the (only) minio-server available in conda-forge is newer than what arrow supports, and so we need to hack the fixtures a little. This only concerns the test suite and should otherwise be unproblematic (before it didn't get tested at all!).

**Comment by h-vetinari** [comment]
@conda-forge/arrow-cpp, would be happy for reviews or feedback here :)

**Review by xhochy — APPROVED** [review]
There are probably ways to speed up the build a bit but from the content-perspective, this PR looks good to me.

**Comment by h-vetinari** [comment]
Thanks for the review! :)

**Comment by jorisvandenbossche** [comment]
@h-vetinari thanks a lot for finishing this splitting!

As a follow-up, should we add a `pyarrow-base` or `pyarrow-core` (I think both suffixes are being used) that only depends on `libarrow`?

**Comment by raulcd** [comment]
I was planning on trying to work on this during the next couple of weeks now that this has been merged and I have released 14.0.1.

**Comment by h-vetinari** [comment]
> As a follow-up, should we add a `pyarrow-base` or `pyarrow-core` (I think both suffixes are being used) that only depends on `libarrow`?

Based on discussion in https://github.com/apache/arrow/issues/38536 and the work towards that which went into arrow 14 already, I think we should definitely try!

> I was planning on trying to work on this during the next couple of weeks now that this has been merged and I have released 14.0.1.

Great!

**Pull request merged**
