### PR TITLE
Update to HEAD

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Comment by xhochy** [comment]
Conda currently lacks optional requirements and as the `jemalloc` requirement is quite small, it made it a real requirement: https://github.com/conda/conda/issues/793

**Comment by wesm** [comment]
@xhochy do you know why the OS X build is failing?

**Comment by xhochy** [comment]
jemalloc on OSX in the latest version needed an `#define`. Fixed upstream in `arrow`, now the build is green.

**Comment by wesm** [comment]
I believe there are some API changes that may break pyarrow, so we'll want to update the parquet-cpp and pyarrow packages as soon as possible

**Comment by xhochy** [comment]
Will do immediately!

**Pull request merged**
