### PR TITLE
[main] bail out of activation if environment is not writable

### LINKED ISSUE #1126: Activating read-only conda environment with arrow installed
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

When we create a conda environment with this package installed in a read-only environment I get the following error when I attempt to activate the environment. 

```shell
mkdir: cannot create directory ‘/home/conda/rag-llm/envs/rag-llm-ai-toolbox/share/gdb/auto-load//home/conda/rag-llm/envs’: Permission denied
ln: failed to create symbolic link '/home/conda/rag-llm/envs/rag-llm-ai-toolbox/share/gdb/auto-load//home/conda/rag-llm/envs/rag-llm-ai-toolbox/lib/libarrow.so.1100.0.0-gdb.py': No such file or directory
/home/conda/rag-llm/envs/rag-llm-ai-toolbox/etc/conda/activate.d/libarrow_activate.sh ERROR: Failed to create symlink from '/home/conda/rag-llm/envs/rag-llm-ai-toolbox/share/gdb/auto-load/replace_this_section_with_absolute_slashed_path_to_CONDA_PREFIX/lib/libarrow.so.1100.0.0-gdb.py' to '/home/conda/rag-llm/envs/rag-llm-ai-toolbox/share/gdb/auto-load//home/conda/rag-llm/envs/rag-llm-ai-toolbox/lib/libarrow.so.1100.0.0-gdb.py'
```

### Installed packages

```shell
Not relevant.
```

### Environment info

```shell
Not relevant.
```

### PR DESCRIPTION
**Pull request by h-vetinari**
Reinstate 7c0287a84ba8303b12c97e397f2b24a0239b6b46

Closes #1126

Also pick up some small improvements from #1124

### CODE REVIEW

**Comment by maresb** [comment]
What's the purpose of the GDB wrappers in the first place? (Despite having contributed I don't actually understand what's going on. :joy:)

**Comment by h-vetinari** [comment]
> What's the purpose of the GDB wrappers in the first place?

gdb needs to know where to look for symbols, and has a very specific path pattern it expects. Since that pattern depends on the exact path of the environment (which we cannot know at packaging time), the only option is to do something with an activation script (or not at all).

But where that approach is not possible, we might as well drop gdb support. It's not that important.

**Comment by maresb** [comment]
Ok, so it's only if someone wants to use a debugger with libarrow? That doesn't sound so important.

Maybe we should modify the log message to say so?

> If you don't plan to use the GDB debugger with libarrow, then this warning can be safely ignored.

**Comment by h-vetinari** [comment]
> Ok, so it's only if someone wants to use a debugger with libarrow? That doesn't sound so important.

Yes and yes.

> Maybe we should modify the log message to say so?

OK

**Review by maresb — APPROVED** [review]
This is great, thanks for this!

Maybe we want to also add something similar to `ERROR: Failed to create symlink...`?

**Comment by h-vetinari** [comment]
I've switched off my laptop already. Perhaps the next time. ;)
Or feel free to submit a PR that switches the error to (visible by default) warning. 🙃

**Pull request merged**
