### PR TITLE
Package Flight SQL

### PR DESCRIPTION
**Pull request by lidavidm**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Enable the Flight SQL build. This doesn't have any additional dependencies.

### CODE REVIEW

**Review by xhochy — APPROVED** [review]

**Comment by lidavidm** [comment]
Hmm, I'm going to have to debug that Windows issue (and figure out why our existing CI doesn't catch it). Do we prefer dropping Flight SQL from Windows and proceeding for now, or just holding off with this until 9.0.0 (assuming I get in a fix)?

**Comment by xhochy** [comment]
If the fix is small, we can also apply a patch on top of 8.0.0 here.

**Comment by lidavidm** [comment]
Looks like some of the builds tend to time out (maybe adding Flight SQL is pushing us above the threshold) - wonder if there's some way to speed up the builds or trim things we don't need. I know some of the Arrow CI builds enable unity builds to try to speed things up, maybe that's worth trying here?

**Comment by kkraus14** [comment]
> Looks like some of the builds tend to time out (maybe adding Flight SQL is pushing us above the threshold) - wonder if there's some way to speed up the builds or trim things we don't need. I know some of the Arrow CI builds enable unity builds to try to speed things up, maybe that's worth trying here?

I tried requeueing but we're hitting timeouts on emulated builds here. We should probably try to move towards cross compilation but that's a relatively big lift.

**Comment by jakirkham** [comment]
Unfortunately cross-compiling and CUDA builds don't work together today.

**Comment by kkraus14** [comment]
> Unfortunately cross-compiling and CUDA builds don't work together today.

Doesn't that only apply to device code requiring nvcc? The arrow package just uses the CUDA driver API without any actual device code. We should be able to cross compile against a libcuda stub?

**Comment by jakirkham** [comment]
Which means we need to use the CUDA Docker images. This is part of the issue.

**Review by kkraus14 — APPROVED** [review]

**Comment by kkraus14** [comment]
Any issues with merging this without all of the emulated builds passing? I can then babysit the merge commit jobs to make sure we get packages published.

**Comment by jakirkham** [comment]
None. Though it looks like we are down to one.

**Comment by kkraus14** [comment]
> None. Though it looks like we are down to one.

Will give this a chance to finish its run, but if it fails lets merge.

**Comment by lidavidm** [comment]
Thanks everyone!

**Comment by h-vetinari** [comment]
> > > Unfortunately cross-compiling and CUDA builds don't work together today.
> >
> > Doesn't that only apply to device code requiring nvcc? The arrow package just uses the CUDA driver API without any actual device code. We should be able to cross compile against a libcuda stub?
> Which means we need to use the CUDA Docker images. This is part of the issue.

I think I figured out the images part (or at least the rendering part) in #859. Meaning we have x86 build compilers, but I don't yet know how we get the libcuda stub for host (aarch/ppc) into there. We might be able to download it in the build scripts...?

**Comment by kkraus14** [comment]
> We might be able to download it in the build scripts...?

You're not allowed to redistribute a libcuda stub in a container unless the container was based on the `nvidia/cuda` container.

**Comment by h-vetinari** [comment]
> You're not allowed to redistribute a libcuda stub in a container unless the container was based on the `nvidia/cuda` container.

I propose to continue the discussion in #859, if that's alright.

**Pull request merged**
