### PR TITLE
Pinning libprotobuf=3.6.*

### PR DESCRIPTION
**Pull request by gabrielcnr**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by gabrielcnr** [comment]
@marcelotrevisani - as discussed, this fixes an `ImportError` when picking up `>=3.6`

**Review by xhochy — CHANGES_REQUESTED** [review]
No, we're not diverting from the global pinning here.

**Comment by xhochy** [comment]
@gabrielcnr Can you please provide further context here?

**Comment by gabrielcnr** [comment]
Had this problem in a complex environment I have here... subset of the problem can be reproduced by creating an environment like the one below:

```
mamba create -n ibis ibis-framework==0.14.0 python=3.6 “pyarrow>=0.13.0,<0.14” sqlalchemy=1.3 -y -c Conda-forge
```

And then trying to `import ibis` in Python will crash with an ImportError because of protobuf...

**Comment by xhochy** [comment]
That is a really old `pyarrow` version, that will not be fixed by breaking the 3.0 build.

**Comment by xhochy** [comment]
@gabrielcnr This rather seems like one of the packages you have installed which is not `pyarrow` has a dependency on `protobuf` *and* `libprotobuf` but did only declare on the first and thus didn't get a strict pin.

**Comment by gabrielcnr** [comment]
@xhochy - it makes sense, it's an old `pyarrow` and won't be able to upgrade quickly right now. I'm happy to pin `libprotobuf` to be `3.6.*` on the target environment. This solves my problem. The PR can be closed then. Thanks.

**Comment by xhochy** [comment]
I'm a bit confused though as `pyarrow` should already have such a strict `libprotobuf` pin.

**Comment by marcelotrevisani** [comment]
I believe we can merge that in a separated branch for that pyarrow version, it will fix it

**Comment by xhochy** [comment]
We have a pin for `https://github.com/conda-forge/arrow-cpp-feedstock/blob/d8bc9d0450b2e053fddf9eab481614a0da37609d/.ci_support/linux_python3.6.yaml#L17-L18` `libprotobuf=3.7`. So I'm confused why it works with an older version.

**Comment by marcelotrevisani** [comment]
that is odd indeed. I thought the older version was using protobuf 3.6

**Comment by marcelotrevisani** [comment]
unnn... maybe it is getting that package that was generated from the archived feedstock?

**Comment by marcelotrevisani** [comment]
> unnn... maybe it is getting that package that was generated from the archived feedstock?

That is not the case. I just verified. Yeah... very intriguing

**Pull request closed without merging**
