### PR TITLE
[15.x] Migrate ucx116

### PR DESCRIPTION
**Pull request by xhochy**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
@h-vetinari Rerendering fails with 

```
ValueError: variant config in /Users/uwe/Development/conda-forge/arrow-cpp-feedstock/recipe/conda_build_config.yaml is ambiguous because it
does not fully implement all zipped keys (To be clear: missing ['fortran_compiler_version', 'c_stdlib_version', 'cdt_name', 'cuda_compiler', 'cuda_compiler_version', 'docker_image'])
or specifies a subspace that is not fully implemented (To be clear:
.. we did not find ['13', '10'] from {'c_compiler_version': ['13', '10', '11'], 'cxx_compiler_version': ['13', '10', '11']} in c_compiler_version:['12', '11']).
```

Do you have an idea what changed and what we do need to adjust?

**Comment by xhochy** [comment]
Ah! This is probably related to CUDA?

**Comment by h-vetinari** [comment]
> Ah! This is probably related to CUDA?

It's related to [this](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5799#issuecomment-2071525461). I argued not to do this in the core call, but was in the minority. You need https://github.com/conda-forge/arrow-cpp-feedstock/pull/1376/commits/0fc822becf4579b8ae1994d4dfb2ae2b5f534500 to fix it. However, unless there's a big hurry for ucx, I'd like to get #1376 in first and then deal with the various migrations.

**Comment by xhochy** [comment]
OK, then let's wait a bit.

**Pull request merged**
