### PR TITLE
Update boost pin

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by jschueller** [comment]
@conda-forge-admin, please rerender

**Comment by xhochy** [comment]
This sadly fails on Windows.

@MaxRis would be nice if you could have a short look. Maybe you see why boost_filesystem is not found.

**Comment by MaxRis** [comment]
@xhochy best guess, it's because "boost-cpp 1.66.0" is requested with this changes and bld.bat relies on VS 2015 (vc14_0)  as build tool in this line: "cmake -G "Visual Studio 14 2015 Win64"". But boost-cpp package for VS 2015 (vc14_0) is not available in conda. Currently, `boost-cpp:      1.66.0-vc14_1 conda-forge [vc14]` is installed, which is built with VS 2017 (vs14_1). That's why, seems, headers are found fine, but libs are, probably, incompatible and errors out on linkage stage.

**Comment by jschueller** [comment]
No, in vc14_1 , 1 is the build number, not vs 2017.

**Comment by MaxRis** [comment]
@jschueller looks like, I've checked dependencies of dlls installed with vc14_1 and they linked with "MSVCP140.DLL"

**Comment by jschueller** [comment]
Yup, we dont build anything against vs2017 for now (maybe for python 3.7)

**Comment by xhochy** [comment]
Fixed via #45

**Pull request closed without merging**
