### PR TITLE
Build Gandiva 

### PR DESCRIPTION
**Pull request by kszucs**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kszucs** [comment]
Dear @conda-forge/core! 

We need to use clang to compile llvm bitcode, but I'm struggling to make it work on linux. 
Any advise?

cc @xhochy

**Comment by isuruf** [comment]
clangdev 7 on linux is crippled due to using anaconda compilers. There was a patch by @chrisburr to fix this for clangdev 5, but this was not ported to clangdev 7.

**Comment by kszucs** [comment]
@isuruf could You point me to that patch please?

**Comment by isuruf** [comment]
https://github.com/conda-forge/clangdev-feedstock/pull/46

**Comment by xhochy** [comment]
The cleanest solution is definitely to add the clang sysroot handling but we can workaround this by manually specify the missing include directories as we do in the `manylinux1` build: https://github.com/apache/arrow/blob/4495305092411e8551c60341e273c8aa3c14b282/python/manylinux1/build_arrow.sh#L80

**Comment by xhochy** [comment]
I'm playing a bit around in https://github.com/conda-forge/arrow-cpp-feedstock/pull/78, let's see how far that goes.

**Comment by isuruf** [comment]
clangdev 8 has patches to detect the gcc sysroot, but it seems arrow-cpp needs llvm 7.0. If you can backport the small patches in https://github.com/conda-forge/clangdev-feedstock/tree/master/recipe/patches to clangdev 7, you'll be able to use clangdev 7.

**Comment by kszucs** [comment]
@isuruf yep, arrow depends on llvm 7. How could I backport the sysroot patch to clangdev 7? Do I need to build llvmdev or do I need to submit a PR to the clangdev-feedstock?

**Comment by isuruf** [comment]
You only need to submit a PR to clangdev-feedstock to backport https://github.com/conda-forge/clangdev-feedstock/tree/master/recipe/patches

**Pull request closed without merging**
