### PR TITLE
Backport #40412 to `15.0.2`

### PR DESCRIPTION
**Pull request by galipremsagar**
This PR backports a python memory leak patch to `15.0.2`: https://github.com/apache/arrow/pull/40412

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by galipremsagar** [comment]
@conda-forge-admin, please rerender

**Review by h-vetinari — APPROVED** [review]
Thanks!

**Comment by galipremsagar** [comment]
> Also: great effort for a first PR 💪

Thanks @h-vetinari ! It was @jakirkham's guidance 🙌  Could you re-start the failing jobs again? Looks like these seem to be flaky network issues

**Comment by galipremsagar** [comment]
@h-vetinari Do you know if there is a known issue with `linux_aarch64_c_compiler_version12cuda_compiler_versionNonecxx_compiler_version12` runners? I see these consistently get disconnected from azure pipelines even in https://github.com/conda-forge/arrow-cpp-feedstock/pull/1369

**Comment by galipremsagar** [comment]
@conda-forge-admin, please rerender

**Review by h-vetinari — APPROVED** [review]

**Pull request merged**
