### PR TITLE
[8.0.x] Feature sync with main & upstream

### PR DESCRIPTION
**Pull request by h-vetinari**
Combination of #853 & #848 for 8.0.x

I double-checked when the features (enabled in a807519732ed911f00077c7290423e896c797741) landed:
* 6.0: https://github.com/apache/arrow/commit/1d139fefdee42aff59bfaef41e51c9cf02f7f1f3
* 8.0: https://github.com/apache/arrow/commit/4e1ba5725480d01e18be6e52a0bc3fb4e5781442
* 9.0: https://github.com/apache/arrow/commit/7b5912deea1c0fc8e2ac801b99d2448f387fa98e

However, despite `ARROW_GCS` seemingly landing in 9.0, it was enabled here in https://github.com/conda-forge/arrow-cpp-feedstock/pull/677 during the 7.0 cycle.

CC @xhochy @pitrou @kkraus14

### CODE REVIEW

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
So I don't fully get the relationship between gandiva & jemalloc (there should be none?), but in any case, this works if I backport https://github.com/apache/arrow/commit/2c87e81a77d983ddccce602af867710708e37ff6, or presumably I could kick out https://github.com/conda-forge/arrow-cpp-feedstock/pull/860/commits/6f7877536489f8dd90a2c8ed094db7f1e3c5cf22

Any preferences which approach I should take? If it were up to me, I'd backport the jemalloc version bump (& gandiva enablement) back until 6.0.x.

WDYT @xhochy @pitrou @kkraus14?

**Comment by kkraus14** [comment]
I'd be more in favor of backporting https://github.com/apache/arrow/commit/2c87e81a77d983ddccce602af867710708e37ff6

**Comment by h-vetinari** [comment]
> I'd be more in favor of backporting [apache/arrow@2c87e81](https://github.com/apache/arrow/commit/2c87e81a77d983ddccce602af867710708e37ff6)

There are now passing builds (with the same approach) for [7.0.x](https://github.com/conda-forge/arrow-cpp-feedstock/pull/863) and [6.0.x](https://github.com/conda-forge/arrow-cpp-feedstock/pull/864) as well. Key part being the gandiva enablement on osx-arm back to 6.0

**Comment by h-vetinari** [comment]
@conda-forge/arrow-cpp 

If someone has concerns / objections to backporting gandiva-on-osx-arm & a jemalloc bump (also mostly for osx-arm) back to all supported versions in conda-forge (until 6.0.x), please let me know.

In case there are no further comments, I'll merge this & #863 & #864 on the weekend.

PS. These PRs also contain some further clean-ups & make the branches consistent (as much as possible/reasonable) with main resp. https://github.com/apache/arrow/pull/14102

**Review by kkraus14 — APPROVED** [review]
LGTM, but I'm technically not a maintainer on this recipe 😆

**Pull request merged**
