### PR TITLE
Switch to more specific (=smaller) bindings for GCP

### LINKED ISSUE #1305: Consider switching to `libgoogle-cloud-storage` from `google-cloud-cpp`.
### Comment:

We have split `google-cloud-cpp` (https://github.com/conda-forge/google-cloud-cpp-feedstock/issues/141) this package can depend on a much smaller dependency:

https://anaconda.org/conda-forge/libgoogle-cloud-storage

and 

https://anaconda.org/conda-forge/libgoogle-cloud-storage-devel

Should be all it needs.

### PR DESCRIPTION
**Pull request by h-vetinari**
This needed a bunch of work on the google-cloud-cpp side (see [here](https://github.com/conda-forge/google-cloud-cpp-feedstock/issues/141)), but now we should hopefully be able to reap the benefits!

Closes #1305 

~Currently based on #1312, draft until that goes in.~

### CODE REVIEW

**Comment by h-vetinari** [comment]
@conda-forge/arrow-cpp this should be ready, PTAL

CC @coryan

**Comment by h-vetinari** [comment]
(Note: I added a couple clean-ups that aren't strictly related to the GCP bindings)

**Review by xhochy — APPROVED** [review]

**Comment by h-vetinari** [comment]
Please don't squash-merge, these commits were intentionally well-separated.

**Comment by xhochy** [comment]
> Please don't squash-merge, these commits were intentionally well-separated.

This wasn't intentional. I just clicked on the default merge button.

**Pull request merged**
