### PR TITLE
14.x: Preserve symlinks

### PR DESCRIPTION
**Pull request by xhochy**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
FYI @jtilly

**Review by h-vetinari — APPROVED** [review]
Would have folded that into the next PR to `14.x`, but this is fine of course. Thanks!

**Comment by xhochy** [comment]
We're a bit on a hunt these days for `pyarrow` installation sizes. Looking forward to the pyarrow split, but this alongside the incoming `ucx` PR already saves a lot.

**Comment by h-vetinari** [comment]
> Looking forward to the pyarrow split, but this alongside the incoming `ucx` PR already saves a lot.

Then you'll also like #1314. ;-)

**Pull request merged**
