### PR TITLE
Remove ucx dependency for now

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
See https://github.com/conda-forge/arrow-cpp-feedstock/issues/962#issuecomment-1433172084

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by h-vetinari** [comment]
Thanks for the PR. You'll have to adapt build.sh as well (it might work without adaptation but it would be confusing). The commit history resp. git blame should be relatively self-explanatory I hope. :)

**Comment by jorisvandenbossche** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
cc @kkraus14

**Comment by jakirkham** [comment]
I'm hoping we can solve this on the `ucx` end instead of needing this change. There is a 1.14.0 release coming up, which would be a good time to coordinate package changes.

We already have a change for `libnuma` in the queue ( https://github.com/conda-forge/ucx-split-feedstock/issues/112 ).

For example issue ( https://github.com/conda-forge/ucx-split-feedstock/issues/66 ) proposes folding the CPU & GPU builds into one build and then making `cudatoolkit` a [`run_constrained`]( https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#run-constrained ) dependency (so optional) instead of `run` (required), which drop the need for the selector and drop pulling in `cudatoolkit` (by default)

**Comment by kkraus14** [comment]
I agree that I'd much prefer to fix the UCX package than disable it in the libarrow builds if possible, but understand if there's a short term fix we need to make here in the meantime.

**Comment by jorisvandenbossche** [comment]
Yes, this PR is only meant for "until the ucx issues is solved". But to me it seems quite unsure what would be the exact timeline for getting those fixes in for ucx 1.14 (also just being unfamiliar with the package, I can't judge that), while I would consider the pyarrow issue as a serious regression in user experience (hugely blowing up every environment with pyarrow on linux), something we should fix on the short-term IMO.

**Comment by jorisvandenbossche** [comment]
The timeout on aarch64, is that a known issue? Or could someone restart that build?

**Comment by h-vetinari** [comment]
Let's undo this regression (even though somewhat subjective), and then readd it once ucx is ready.

**Comment by h-vetinari** [comment]
FYI: now that https://github.com/conda-forge/ucx-split-feedstock/pull/111 has landed, I added a PR to re-enable ucx support in https://github.com/conda-forge/arrow-cpp-feedstock/pull/1011

**Pull request merged**
