### PR TITLE
Backport #1116 to v11.x

### PR DESCRIPTION
**Pull request by benfred**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by benfred** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
No need to do the build artefact game here. Once (in #1116) is enough. Could you please remove those commits again, them I'm happy to merge. If possible, please also open a PR for 10.0.x. :)

**Comment by benfred** [comment]
thanks @h-vetinari ! I've removed the build_artifacts here, and will open a PR for v10 shortly

**Comment by benfred** [comment]
@jakirkham I've opened a v9 PR here https://github.com/conda-forge/arrow-cpp-feedstock/pull/1119 just in case

**Review by h-vetinari — APPROVED** [review]
Thank you! :)

**Comment by h-vetinari** [comment]
> Do we want a PR to `9.0.x` too?

Fine by me. It's a big matrix currently (with protobuf 3 & 4), but it's still supported until we have arrow 13.

**Comment by h-vetinari** [comment]
The CI here is going to fail due to #1114, so automerge makes no sense. The last run was already green so in it goes 🙃

**Pull request merged**
